app: vjepa_droid
cpus_per_task: 4
folder: /mnt/cycle_jePA_droid
debugmode: true
mem_per_gpu: 40G
nodes: 1
tasks_per_node: 1
data:
  batch_size: 1
  camera_views:
  - wrist_image_left
  crop_size: 128
  datasets:
  - /mnt/droid/droid_100/1.0.0
  dataset_fpcs:
  - 2
  fps: 4
  num_workers: 0
  patch_size: 16
  pin_mem: true
  stereo_view: false
  tubelet_size: 1
meta:
  dtype: float32
  eval_freq: 100
  resume_checkpoint: null
  pretrain_checkpoint: null
  load_predictor: false
  load_encoder: false
  save_every_freq: 10
  seed: 239
  use_sdpa: true
model:
  model_name: vit_giant_xformers
  pred_depth: 24
  pred_embed_dim: 1024
  pred_num_heads: 16
  uniform_power: true
  use_activation_checkpointing: true
  use_extrinsics: false
  use_rope: true
  use_cycle_loss: true
  cycle_alpha: 0.5
  cycle_pred_depth: 4
  backward_lr_scale: 0.1
loss:
  auto_steps: 1
  loss_exp: 1.0
  normalize_reps: true
  reg_coeff: 0.0
optimization:
  anneal: 5
  epochs: 1
  final_lr: 0.0
  final_weight_decay: 0.04
  ipe: 100
  lr: 0.0001
  start_lr: 0.00001
  warmup: 3
  weight_decay: 0.04
